"""empty message

Revision ID: 06115ee68a16
Revises: 331167db996e
Create Date: 2026-05-28 11:33:35.632617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06115ee68a16'
down_revision = '331167db996e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thrownkeyword',
    sa.Column('kid', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('kid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thrownkeyword')
    # ### end Alembic commands ###
