"""empty message

Revision ID: 2062b2e8b14d
Revises: c078d6a937e3
Create Date: 2026-08-20 18:21:54.630523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2062b2e8b14d'
down_revision = 'c078d6a937e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ninjasearch',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('cursor', sa.String(length=1000000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ninjasearch')
    # ### end Alembic commands ###
