"""empty message

Revision ID: 331167db996e
Revises: 6dcb96a1ef3b
Create Date: 2026-05-28 10:52:23.158175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331167db996e'
down_revision = '6dcb96a1ef3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thowncompany',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('cid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thowncompany')
    # ### end Alembic commands ###
